config/routes.rb
ThirtySecondLaugh::Application.routes.draw do
  
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    post "logout" => "devise/sessions#destroy"
  end

  # get 'update-fb-like/:id', :to => 'clips#update_fb', :as => :update_fb
  root :to => 'welcome#index'
  
  resources :clips do
    collection do
      get 'popular'
      get 'latest'
      get 'tv'
      post :rate
      get 'preload_left_video'
      get 'preload_right_video'
    end
    member do
      get 'update_modal'
      put 'add_collect'
      put 'remove_collect'
    end
  end

  get 'category/:category', :to => 'category#index', :as=> :clips_category
  post 'clips/search', :to => 'clips#search', :as=> :clips_search
  get 'add_tag(/:tag)', :to => 'clips#add_tag', :as => :add_tag
  resources :users
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  
  acts_as_taggable_on :tags,:category
  

  has_many :user_collect_clips
  has_many :clip_collect_by_users, :through => :user_collect_clips, :source => :user

  has_many :user_rated_clips
  has_many :rated_by_users, :through => :user_rated_clips, :source => :user

  scope :popular, where('is_hot = ?', 1).order('updated_at DESC')
  scope :by_date, order('created_at DESC') 

  auto_html_for :url do
    html_escape
    image
    youtube(:width => 640, :height => 400)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  # search
  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :id, type: 'integer'
    indexes :title
    indexes :discription
    indexes :tag_name
    indexes :category_name
  end

  def self.search(params)
    tire.search(load: true) do
      query { string params[:search] } if params[:search].present?
    end
  end


  self.include_root_in_json = false
  def to_indexed_json
    to_json(methods: [:tag_name])
  end

  def tag_name
    tags.join(" "){|t| t.name}
  end

  def category_name
    category.join(" "){|t| t.name}
  end

  def self.parse_video_id url
    %r|http://www.youtube.com/watch\?v=(.*)| =~ url
    $1[0..10]
  end
end

app/controllers/clips_controller.rb
# encoding: utf-8

class ClipsController < ApplicationController
  def update_modal
    @clip = Clip.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def tv
  end


  def search
    @clips = Clip.search(params)
  end

  def add_collect
    @clip = Clip.find(params[:id])     
    current_user.collect_clips << @clip
    @btn_text = "已收藏"
    @btn_class = "btn btn-danger"
    respond_to do |format|
      format.js
    end
  end

  def remove_collect
    @clip = Clip.find(params[:id])
    current_user.collect_clips.delete @clip
    @btn_text = "收藏"
    @btn_class = "btn btn-success"
    respond_to do |format|
      format.js
    end
  end

  def new
    @clip = Clip.new
    @tags = Clip.tag_counts_on(:cagtegory) + Clip.tag_counts_on(:tags)
  end

  def create
    @clip = Clip.new(params[:clip])
    @clip.tag_list = params[:text][:tag_area]
    @clip.video_id = Clip.parse_video_id params[:clip][:url]

    if @clip.save
      redirect_to root_path
    else
      render :action => :new
    end
    # redirect_to board_topic_path(@topic.board,@topic)
  end

  def add_tag
    @tag = params[:tag]
    respond_to do |format|
      format.js
    end
  end

  def show
    @clip = Clip.find(params[:id])
    @recomment_clips = Clip.all
  end

  def rate
    rate = current_user.user_rated_clips.build
    rate.rating = params[:rating]
    rate.clip_id = params[:clip_id]
    rate.save
    respond_to do |format|
      format.js
    end
  end

  def preload_left_video
    @clip = Clip.find(rand(Clip.count))
  end

  def preload_right_video
    @clip = Clip.find(rand(Clip.count))
  end

  def popular
    @clips = Clip.popular.paginate(:per_page => 10, :page => params[:page])
  end

  def latest
    @clips = Clip.by_date.paginate(:per_page => 10, :page => params[:page])
  end
end

app/helpers/clips_helper.rb
module ClipsHelper
  def star_button(f, clip, value, checked)
    if value == checked
      radio_button("rating[#{clip.id}]","", value,:name => "rating", :class => 'star', "data-clip" => clip.id, :checked => "checked")
    else
      radio_button("rating[#{clip.id}]","", value,:name => "rating", :class => 'star', "data-clip" => clip.id)
    end
  end
end

app/views/clips/_crousel_item.html.haml
.item
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "349", :src => "http://www.youtube.com/embed/FKWwdQu6_ok?version=3&enablejsapi=1", :width => "425"}

app/views/clips/add_collect.js.erb
$('#btn-collect-<%= @clip.id %>').remove();
$('.count-info.collect-clip.<%=@clip.id%>').append("<%= escape_javascript render '_partials/collect_button', :clip => @clip, :url => remove_collect_clip_path(p), :style => 'btn btn-danger', :str => '已收藏' %>");

app/views/clips/add_tag.js.erb
$('#text_tag_area').addTag("<%=@tag%>");

app/views/clips/latest.html.haml
.offset1
.span12
  = will_paginate(@clips,:style => "display: none; ")
  =render :partial => "_partials/clips_show", :locals => {:clips => @clips}

app/views/clips/new.html.haml
= javascript_include_tag "jquery.tagsinput.min.js"
= stylesheet_link_tag    "jquery.tagsinput.css"

= simple_form_for @clip, :url => clips_path, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title, :input_html => { :class => "span6" }, :hint => '輸入一個適切又好笑標題吧！', :label => "影片標題："
  = f.input :url, :input_html => { :class => "span6" }, :hint => '直接貼上網址就可以囉', :label => "影片網址："
  = f.input :discription, :input_html => { :class => "span6", :rows => 5}, :label => "影片描述："
  .control-group.text.optional
    %label.text.optional.control-label
      加入標籤：
    .controls
      = tag_autocomplete_js 'text_tag_area'
      = text_area :text ,"tag_area",:cols => false, :rows => false, :class => "control-group"
      可以輸入，也可從右邊點選標籤
      - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
        = link_to tag.name, add_tag_path(tag.name), :class => css_class, :remote => true
  .form-actions
    =f.button :submit,"確定", :class => "btn btn-primary"
    %input.btn.btn-danger{:name => "commit", :type => "reset", :value => "取消"}

app/views/clips/popular.html.haml
.offset1
.span12
  = will_paginate(@clips,:style => "display: none; ")
  =render :partial => "_partials/clips_show", :locals => {:clips => @clips}

app/views/clips/preload_left_video.js.erb
$('.carousel-inner').prepend("<%= j render :partial => 'crousel_item', :clip => @clip%>")

app/views/clips/preload_right_video.js.erb
$('.carousel-inner').append("<%= j render :partial => 'crousel_item', :clip => @clip%>")

app/views/clips/remove_collect.js.erb
$('#btn-collect-<%= @clip.id %>').remove();
$('.count-info.collect-clip.<%=@clip.id%>').append("<%= escape_javascript render '_partials/collect_button', :clip => @clip, :url => add_collect_clip_path(p), :style => 'btn btn-success', :str => '收藏' %>");

app/views/clips/search.html.haml
.offset1
.span12
  =render :partial => "_partials/clips_show", :locals => {:clips => @clips}

app/views/clips/show.html.haml
.span8
  .well
    .clip-show-title
      %h1 害人的美女 : 美女讓爸爸看傻了
    .youtube-video
      .video-show-container 
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "349", :src => "http://www.youtube.com/embed/FKWwdQu6_ok", :width => "425"}
  .facebook-comments-box.well
    .fb-comments{"data-href" => "http://example.com", "data-num-posts" => "2", "data-width" => "660"}
.span4
  .well
    = button_to "收藏", "#", :class => "btn btn-success"
  .well
    評分
    = form_for "", :url => rate_clips_path, :remote => true do |f|
      - 1.upto(5) do |value|
        = star_button f, @clip, value, (value)
      = hidden_field_tag("clip_id", @clip.id)
      = f.submit :id => "submit_#{@clip.id}", :style => "display: none; "
  .well
    推薦
    %br
    -@recomment_clips.each do |r|
      .recomment-clip
        .image
          = image_tag "http://img.youtube.com/vi/#{r.video_id}/1.jpg"
        .title
          =r.title

app/views/clips/tv.html.haml
.video-container  
  #myCarousel.carousel.slide
    .carousel-inner
      .active.item
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "349", :src => "http://www.youtube.com/embed/FKWwdQu6_ok?version=3&enablejsapi=1", :width => "425"}
      .item
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "349", :src => "http://www.youtube.com/embed/FKWwdQu6_ok", :width => "425"}
    / End of Carousel Inner
    = link_to "‹", preload_left_video_clips_path, :class => "left carousel-control", "data-slide" => "prev", 'data-target' => "#myCarousel", :remote => true
    = link_to "›", preload_right_video_clips_path, :class => "right carousel-control", "data-slide" => "next", 'data-target' => "#myCarousel", :remote => true

app/views/clips/update_modal.js.erb
$('.modal-body').remove();
$('.modal-footer').remove();
$('.modal-header').after("<%= escape_javascript render '_partials/modal_body', :clip => @clip%>");

FB.XFBML.parse(); 