config/routes.rb
ThirtySecondLaugh::Application.routes.draw do
  
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    post "logout" => "devise/sessions#destroy"
  end

  # get 'update-fb-like/:id', :to => 'clips#update_fb', :as => :update_fb
  root :to => 'welcome#index'
  
  resources :clips do
    collection do
      get 'popular'
      get 'latest'
      get 'tv'
      post :rate
      get 'preload_left_video'
      get 'preload_right_video'
    end
    member do
      get 'update_modal'
      put 'add_collect'
      put 'remove_collect'
    end
  end

  get 'category/:category', :to => 'category#index', :as=> :clips_category
  post 'clips/search', :to => 'clips#search', :as=> :clips_search
  get 'add_tag(/:tag)', :to => 'clips#add_tag', :as => :add_tag
  resources :users
end

app/views/_partials/_clips_show.html.haml
#item_box_container.item_box_container.center
  - clips.each do |p|
    .item_box
      = link_to (image_tag "Play-Button.png", :class => "play-button", :width => "90px"),update_modal_clip_path(p),"data-toggle" => "modal", 'data-target' => "#myModal",:remote => true
      = image_tag "http://img.youtube.com/vi/#{p.video_id}/1.jpg", :width => "240"
      .title
        =link_to p.title, clip_path(p)
      .user-info
        %ul
          .count-info
            = fb_like(clip_path(p))
            = form_for "", :url => rate_clips_path, :remote => true do |f|
              - 1.upto(5) do |value|
                = star_button f, p, value, p.rating
              = hidden_field_tag("clip_id", p.id)
              = f.submit :id => "submit_#{p.id}", :style => "display: none; "
          .count-info.collect-clip{:class => "#{p.id}"}
            - if current_user
              - if current_user.collect(p)
                = button_to "已收藏", remove_collect_clip_path(p), :class => "btn btn-danger",:remote => true, :method => :put, :id => "btn-collect-#{p.id}"
              - else
                = button_to "收藏", add_collect_clip_path(p), :class => "btn btn-success",:remote => true, :method => :put, :id => "btn-collect-#{p.id}"
            -else
              = button_to "收藏", "#", :class => "btn btn-success", "data-toggle" => "modal", 'data-target' => "#loginModal", :id => "btn-collect-#{p.id}"

app/views/_partials/_collect_button.html.haml
=button_to str, url , :class => style ,:remote => true, :method => :put, :id => "btn-collect-#{clip.id}"

app/views/_partials/_footer.html.haml
.center
  天天開心@2012
  = link_to "問題與回報", "", :href => "javascript:UserVoice.showPopupWidget();", :title=>"Open feedback & support dialog (powered by UserVoice)"

app/views/_partials/_login.html.haml
#loginModal.modal.hide.fade{:style => "display: none; width:auto;"}
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"} ×
    請先登入
  .modal-body
    Facebook 登入
    =link_to "Facebook", user_omniauth_authorize_path(:facebook)
    %hr
    = form_for(User.new, :url => session_path(User.new)) do |f| 
      = f.label :email
      = f.email_field :email

      = f.label "密碼"
      = f.password_field :password
      %br
      = f.submit "登入"
      or 
      = link_to "註冊",new_registration_path(User.new)

app/views/_partials/_modal_body.html.haml
.modal-body
  =clip.url_html
      
.modal-footer
  %p
  .fb-like{"data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "30"}

app/views/_partials/_sidebar.html.haml
.well
  分類
  %ul.nav.nav-list
    %li= link_to "人物", clips_category_path("人物")
    %li= link_to "動物", clips_category_path("動物")
    %li= link_to "動畫", clips_category_path("動畫")
    %li= link_to "嬰幼兒", clips_category_path("嬰幼兒")
    %li= link_to "寵物", clips_category_path("寵物")
    %li= link_to "廣告", clips_category_path("廣告")
    %li= link_to "生活", clips_category_path("生活")
    %li= link_to "節目", clips_category_path("節目")
    %li= link_to "運動", clips_category_path("運動")
.well
  熱門關鍵字
  .tags
    - tag_cloud(tags, %w(css1 css2 css3 css4)) do |tag, css_class|
      = link_to tag.name, clips_category_path(tag.name), :class => css_class

app/views/_partials/_topbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container{:style => "width: auto;"}
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse
        %ul.nav
          %li.active
            = link_to "天天開心", root_path
          %li
            =link_to "首頁", root_path
          %li
            = link_to "熱門", popular_clips_path
          %li
            =link_to "最新",latest_clips_path
          %li
            = link_to "一直笑",tv_clips_path
        .navbar-search
          = form_tag clips_search_path, :method => :post do
            = text_field_tag "search","",:class => "search-query span3", :placeholder => "Search"
            .icon-search
        .pull-right
          - if current_user
            = button_to "登出",logout_path, :class => "btn btn-warning"
          - else
            = button_to "登入 or 註冊", new_user_session_path,:class => "btn btn-info"

app/views/_partials/_video_show.html.haml
#myModal.modal.hide.fade{:style => "display: none; width:auto;"}
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"} ×
    太好笑了
  .modal-body
    %object{:style => "height: 390px; width: 640px"}
      %param{:name => "movie", :value => "http://www.youtube.com/v/fRJ5vcXRD7Y?version=3&feature=player_detailpage"}
        %param{:name => "allowFullScreen", :value => "true"}
          %param{:name => "allowScriptAccess", :value => "always"}
            %embed{:allowScriptAccess => "always", :allowfullscreen => "true", :height => "360", :src => "http://www.youtube.com/v/fRJ5vcXRD7Y?version=3&feature=player_detailpage", :type => "application/x-shockwave-flash", :width => "640"}/
      
  .modal-footer
    %p
    .fb-like{"data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "30"}