config/routes.rb
ThirtySecondLaugh::Application.routes.draw do
  
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  } do
    post "logout" => "devise/sessions#destroy"
  end

  # get 'update-fb-like/:id', :to => 'clips#update_fb', :as => :update_fb
  root :to => 'welcome#index'
  
  resources :clips do
    collection do
      get 'popular'
      get 'latest'
      get 'tv'
      post :rate
      get 'preload_left_video'
      get 'preload_right_video'
    end
    member do
      get 'update_modal'
      put 'add_collect'
      put 'remove_collect'
    end
  end

  get 'category/:category', :to => 'category#index', :as=> :clips_category
  post 'clips/search', :to => 'clips#search', :as=> :clips_search
  get 'add_tag(/:tag)', :to => 'clips#add_tag', :as => :add_tag
  resources :users
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= yield :title
    %meta{:charset => "utf-8"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=102372936573191";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    :javascript
      var uvOptions = {};
      (function() {
        var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
        uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/M2RBcl2BRrd4KVeC5FJ8hg.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
      })();
    .feedback
      =link_to image_tag("share.jpg"),new_clip_path
    #container
      #topbar.topbar
        =render :partial => "_partials/topbar"
      #body.container-fluid
        .row-fluid
          =yield
    .facebook_like_box
      = render :partial => "_partials/facebook_like_box"
    %footer
      =render :partial => "_partials/footer"